# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
# Step 1: Install .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x' # Specify your .NET version

# Step 2: Restore dependencies
- script: dotnet restore
  displayName: 'Restore dependencies'

# Step 3: Build the solution
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build solution $(buildConfiguration)'

# Step 4: Run tests (Optional)
# Uncomment if you have tests
# - script: dotnet test --configuration $(buildConfiguration)
#   displayName: 'Run tests'

# Step 5: Publish the application
- script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish application'

# Step 6: Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
  displayName: 'Publish build artifacts'
